from _typeshed import Incomplete

from .logger import trace as trace

__all__ = [
    "baditems",
    "badobjects",
    "badtypes",
    "code",
    "errors",
    "freevars",
    "getmodule",
    "globalvars",
    "nestedcode",
    "nestedglobals",
    "outermost",
    "referredglobals",
    "referrednested",
    "trace",
    "varnames",
]

def getmodule(object, _filename: Incomplete | None = None, force: bool = False): ...
def outermost(func): ...
def nestedcode(func, recurse: bool = True): ...
def code(func): ...
def referrednested(func, recurse: bool = True): ...
def freevars(func): ...
def nestedglobals(func, recurse: bool = True): ...
def referredglobals(func, recurse: bool = True, builtin: bool = False): ...
def globalvars(func, recurse: bool = True, builtin: bool = False): ...
def varnames(func): ...
def baditems(obj, exact: bool = False, safe: bool = False): ...
def badobjects(obj, depth: int = 0, exact: bool = False, safe: bool = False): ...
def badtypes(obj, depth: int = 0, exact: bool = False, safe: bool = False): ...
def errors(obj, depth: int = 0, exact: bool = False, safe: bool = False): ...
