from _typeshed import Incomplete, SupportsRichComparisonT
from collections.abc import Generator
from typing import Callable, Generic, Iterable, TypeVar
from typing_extensions import Any, Concatenate, ParamSpec, Self

__version__: str
__credits__: str

_P = ParamSpec("_P")
_T = TypeVar("_T")
_U = TypeVar("_U")

class Pipe(Generic[_T, _U]):
    function: Callable[Concatenate[Iterable[_U], ...], Iterable[_T]]
    def __init__(self, function: Callable[_P, Iterable[_T]], *args: Any, **kwargs: Any) -> None: ...
    def __ror__(self, other: Iterable[_U]) -> Iterable[_T]: ...
    def __call__(self, f: Callable[Concatenate[Iterable[_U], _P], Iterable[_T]]) -> Self: ...

@Pipe
def take(iterable: Iterable[_U], qte: int) -> Generator[_U, None, None]: ...
@Pipe
def tail(iterable: Iterable[_U], qte: int) -> Iterable[_U]: ...
@Pipe
def skip(iterable: Iterable[_U], qte: int) -> Generator[_U, None, None]: ...
@Pipe
def dedup(iterable: Iterable[_U], key: Callable[[_U], SupportsRichComparisonT | _U] = ...) -> Generator[_U, None, None]: ...
@Pipe
def uniq(iterable: Iterable[_U], key: Callable[[_U], SupportsRichComparisonT | _U] = ...) -> Generator[_U, None, None]: ...

enumerate: Pipe[tuple[int, _U], _U] # pyright: ignore[reportGeneralTypeIssues]

@Pipe
def permutations(iterable: Iterable[_U], r: int | None = None) -> Generator[_U, None, None]: ...
@Pipe
def netcat(to_send: Iterable[Any], host: str, port: int) -> Generator[Any, None, None]: ...
@Pipe
def traverse(args: Iterable[Any]) -> Generator[Any, Incomplete, None]: ...
@Pipe
def tee(iterable: Iterable[_U]) -> Generator[_U, None, None]: ...
@Pipe
def select(iterable: Iterable[_U], selector: Callable[[_U], _T]) -> Iterable[_T]: ...

map: Pipe[_T, _U] # pyright: ignore[reportGeneralTypeIssues]

@Pipe
def where(iterable: Iterable[_U], predicate: Callable[[_U], object]) -> Iterable[_U]: ...

filter: Pipe[_U, _U] # pyright: ignore[reportGeneralTypeIssues]

def take_while(iterable, predicate): ...
def skip_while(iterable, predicate): ...
def groupby(iterable, keyfunc): ...
def sort(iterable, key: Incomplete | None = None, reverse: bool = False): ...
def reverse(iterable): ...
def t(iterable, y): ...
def transpose(iterable): ...
def batched(iterable, n) -> Generator[Incomplete, None, None]: ...

chain: Incomplete
chain_with: Incomplete
islice: Incomplete
izip: Incomplete
