from _typeshed import Incomplete
from collections.abc import Generator

__version__: str
__credits__: str

class Pipe:
    function: Incomplete
    def __init__(self, function, *args, **kwargs) -> None: ...
    def __ror__(self, other): ...
    def __call__(self, *args, **kwargs): ...

def take(iterable, qte) -> Generator[Incomplete, None, None]: ...
def tail(iterable, qte): ...
def skip(iterable, qte) -> Generator[Incomplete, None, None]: ...
def dedup(iterable, key=...) -> Generator[Incomplete, None, Incomplete]: ...
def uniq(iterable, key=...) -> Generator[Incomplete, None, Incomplete]: ...

enumerate: Incomplete

def permutations(iterable, r: Incomplete | None = None) -> Generator[Incomplete, Incomplete, None]: ...
def netcat(to_send, host, port) -> Generator[Incomplete, None, None]: ...
def traverse(args) -> Generator[Incomplete, Incomplete, None]: ...
def tee(iterable) -> Generator[Incomplete, None, None]: ...
def select(iterable, selector): ...
map = select

def where(iterable, predicate): ...
filter = where

def take_while(iterable, predicate): ...
def skip_while(iterable, predicate): ...
def groupby(iterable, keyfunc): ...
def sort(iterable, key: Incomplete | None = None, reverse: bool = False): ...
def reverse(iterable): ...
def t(iterable, y): ...
def transpose(iterable): ...
def batched(iterable, n) -> Generator[Incomplete, None, None]: ...

chain: Incomplete
chain_with: Incomplete
islice: Incomplete
izip: Incomplete
